name: jay_shree_ram_computer_center
description: Jay Shree Ram Computer Center Dashboard
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true


dev_dependencies:
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/jay_shree_ram_logo.png"
  min_sdk_android: 21
