name: jay_shree_ram_computer_center
description: Jay Shree Ram Computer Center
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.2.0

dev_dependencies:

flutter:
  uses-material-design: true

  assets:
    - assets/icon/jay_shree_ram_logo.png
